### ISSUE TITLE
python 응용 부분 추가 

### ISSUE THREAD

**Issue by jeonghoonkang** [dkim-04/Achievement#1]
추가 필요해 보이는 내용이 있습니다.

1. 각 application 의 설명을 readme.md 로 작성하고, 해당 디렉토리와 설명이 같이 보이도록 해야합니다.
2. 소스코드에는 모듈별로 __main__ 을 사용해 주세요
3.  주석이나 설명이 적게 작성되어 있습니다. 주석 많이 추가해 주세요. 
4. 소스코드는 다운로드 받으면 바로 실행 가능하도록 작성 바랍니다.

> 참고 예)  https://github.com/nochankyung

**Comment by dkim-04** [comment]
중간 점검
1. 각 Application read.me로 작성하고 해당 디렉토리와 설명 같아 보이도록 했습니다

2. python_응용 코드에 주석 및 설명을 추가했습니다
3. 소스코드는 다운 받으면 바로 실행할 수 있게 csv데이터파일을 넣고 코드를 수정했습니다

해야하는 것
모듈별로 main 사용하고 라이브러리 공부한 것 정리하기

**Comment by jeonghoonkang** [comment]
각각 작업한 파일 URL 여기에 남겨 주세요.

**Comment by jeonghoonkang** [comment]
issue 가 체크 확인되고 종료되면 close 하고. 혹시 다시 open 해야 하면 open 하면 됨

**Comment by dkim-04** [comment]
넵
