### ISSUE TITLE
Visualizing 단어 선택

### ISSUE THREAD

**Issue by jeonghoonkang** [dkim-04/Achievement#2]
일반적으로 많이 사용하는 단어를 사용하면 좋고.

완전히 새로운 단어를 만들어야 하면. 새롭게 구성해도 되는데,

Visualizing  단어는 별로 본적이 없어서,

Visualization 이라는 단어로 바꾸어 주면 더 읽기 편할것 같다는 생각임. 의견 바람.

**Comment by dkim-04** [comment]
visualization으로 바꿔 놓겠습니다. 아무래도 데이터 시각화를 표현한 거라 이 단어가 더 알맞을 것 같네요
